# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pictures/')),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=200)),
                ('github_link', models.CharField(max_length=140)),
                ('deployed_link', models.CharField(max_length=140)),
                ('active_project', models.BooleanField(default=False)),
            ],
        ),
    ]
