# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='active_project',
            field=models.BooleanField(default=True),
        ),
    ]
