# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_auto_20171229_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='active_project',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
